---
- name: Install Nano
  yum:
    name: nano
    state: installed

- name: Install Apache
  yum:
    name: httpd
    state: installed

- name: Start Apache
  service:
    name: httpd
    enabled: yes

- name: Create system user
  user:
    name: tdl-www
    group: apache

- name: Copy Apache Config
  copy:
    src: templates/httpd.conf.j2
    dest: '/etc/httpd/conf/httpd.conf'

- name: Copy Apache VHosts
  copy:
    src: templates/todolist.conf.j2
    dest: '/etc/httpd/conf.d/todolist.conf'

- name: Install ModSSL
  yum:
    name: mod_ssl
    state: installed

- name: Ensure certificate folder exists
  file:
    path: /etc/httpd/ssl
    state: directory
    owner: tdl-www
    group: apache
    mode: 0755

- name: Create self-signed SSL cert
  command: openssl req -new -nodes -x509 -subj "/C=GB/ST=England/L=Leicester/CN=192.168.0.35/" -days 3650 -keyout /etc/httpd/ssl/apache.key -out /etc/httpd/ssl/apache.crt -extensions v3_ca creates=/etc/httpd/ssl/apache.crt

- name: Enable Firewall
  service: name=firewalld state=started enabled=yes

- name: Add Firewall for Port 80
  command: firewall-cmd --zone=public --add-port=80/tcp --permanent

- name: Add Firewall for Port 443
  command: firewall-cmd --zone=public --add-port=443/tcp --permanent

- name: Reload Firewall
  service: name=firewalld state=restarted

- name: Disable SELinux
  selinux:
    state: disabled

- name: Restart Apache
  service:
    name: httpd
    state: restarted
